services:


  admin-app:
    tty: true
    stdin_open: true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build: ./
    container_name: admin-app
    ports:
      - "8001:8001"
    networks:
      - task_bot_network


networks:
  task_bot_network:
    driver: bridge
