FROM python:3.12

WORKDIR /app

COPY database /app/database
COPY admin_app /app

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
