services:
  aerich:
    build: .
    command: ["/bin/sh", "-c", "aerich init -t database.config.TORTOISE_ORM && aerich upgrade"]
    volumes:
      - .:/app
    networks:
      - task_bot_network

  tg-app:
    build: ./tg_app
    container_name: tg-app
    ports:
      - "8000:8000"
    env_file:
      - ./tg_app/.env
    networks:
      - task_bot_network

  admin-app:
    tty: true
    stdin_open: true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build: ./admin_app
    container_name: admin-app
    ports:
      - "8001:8001"
    env_file:
      - ./admin_app/.env
    networks:
      - task_bot_network


networks:
  task_bot_network:
    driver: bridge
